###########################################################################
#  P & D Embedded Systems and Multimedia [H09M0a]
#  Subband-Coding 
#  
#  Mohit Dandekar
#  John O'Callaghan
###########################################################################

TOPDIR = ../../..

SRC =               \
	test_ADPCMdec.c  \
	ADPCM.c       \

TNAME = ADPCMdec
EXECUTABLE = ex_test_$(TNAME).out

BLOCKSIZE = 48  # DO NOT CHANGE FOR UNIT TESTS 


-include $(TOPDIR)/scripts/common.mk
