###########################################################################
#  P & D Embedded Systems and Multimedia [H09M0a]
#  Subband-Coding 
#  
#  Mohit Dandekar
#  John O'Callaghan
###########################################################################

TOPDIR = ../../..

SRC =               \
	test_2bank_FB.c  \
	QMF.c       \

TNAME = 2bank_FB
EXECUTABLE = ex_test_$(TNAME).out


BLOCKSIZE = 48  # DO NOT CHANGE FOR UNIT TESTS 

-include $(TOPDIR)/scripts/common.mk
